### ISSUE TITLE
Bug on lists page display

### ISSUE THREAD

**Issue by smirfolio** [obiba/ng-obiba-mica#918]
**Describe the bug**
In an empty Mica server (Non indexed variables) when creating some Networks/Studies/Datasets and publishing them, then there are not displayed on the portal 

**Expected behavior**
Even if there is no variables the lists have to be displayed 

**Screenshots**
One the Portal search page : 
![image](https://user-images.githubusercontent.com/1859345/53500632-be9da600-3a78-11e9-9d6d-96acf9bff23b.png)

Studies list: 
![image](https://user-images.githubusercontent.com/1859345/53500721-dffe9200-3a78-11e9-8780-004701f02ee2.png)

Datasets list: 
![image](https://user-images.githubusercontent.com/1859345/53500771-f7d61600-3a78-11e9-9f51-326dd6040727.png)

Networks list : 
![image](https://user-images.githubusercontent.com/1859345/53500802-07555f00-3a79-11e9-9572-a4ad00c10a71.png)

**Additional context**
There are no linked/indexed variables

**Comment by smirfolio** [comment]
The indexation of the Taxonomies solve this issue, however we have to deal with a fresh mica installation, with minimum content that don't need taxonomies

**Comment by meek0** [comment]
This error is thrown intentionally when no taxonomy can be found (related to query builder). A similar error is thrown if no vocabulary for that taxonomy is found.

Not sure if the client should do anything.
I'd say either the admin or content manager are responsible for that data (index the taxonomies at least).
