### ISSUE TITLE
Fix Coverage's Table Header

### ISSUE THREAD

**Issue by meek0** [obiba/ng-obiba-mica#958]
Fix the coverage's table header such that it would be always visible.

It would be ideal if only the page's scroll would be used (the table itself would not be scroll-able but rather the window itself, as it is now).

One possible strategy would be to clone the table's header to make use of when the original would be hidden from the window. The clone would be fixed to the top of the window as the user scrolls down the table.

**Comment by smirfolio** [comment]
The Fixed header not working well on responsive mode the (Specially on 1024 devices)
![image](https://user-images.githubusercontent.com/1859345/64870930-3648b200-d612-11e9-93b7-2481b22d01f3.png)

**Comment by kazoompa** [comment]
There are still several scenarios where the fixed column breaks:
- resizing window  
- change to fullscreen mode (I have a fix but still not perfect)

As a long term fix we may want to look into a better approach. There seem to be a lot of discrepancies and weird DOM behaviour (double resize event) that breaks the current fix.
