### ISSUE TITLE
Add Vocabulary Terms in Variable's Search Result Table

### ISSUE THREAD

**Issue by meek0** [obiba/ng-obiba-mica#959]
Must show vocabulary terms in variable's search result table.
To do so, one would have to add the taxonomies attribute name or names in the query.

This might be done through configuration because not all taxonomies are available to all clients (i.e Scales or even Area of Information).

**Comment by kazoompa** [comment]
This is partially completed. Still needs a demo/approval and some more UI changes. Possibly add a config so Drupal admin users can add more taxonomies which their terms may appear in the Search result table.
