### ISSUE TITLE
Hide Search's Taxonomy Drawer

### ISSUE THREAD

**Issue by meek0** [obiba/ng-obiba-mica#960]
A user should be able to show or hide the taxonomy drawer. 

Hiding the drawer would widen the search result table.
Would have to manage the layout for smaller screens (responsiveness of the page).

**Comment by meek0** [comment]
responsiveness for small screen can be achieved by adding `col-sm-12` and keeping the default md or lg column (e.g. col-md-3 or col-lg-3).
this way the element's will take full width on small screens but be as is on large screens.

**Comment by sofiyad** [comment]
Feedback from Isabel and Julie:
Change the buttons for hiding of taxonomy drawer and fullscreen to text buttons. ( just to try the look and decide what is the better option)

**Comment by kazoompa** [comment]
I will add a configuration for letting user decide if they want to have a caption or an icon. In fact, if there are no caption in the translation the fallback will be to use the icons.
