### ISSUE TITLE
Coverage by DCE's Sorting

### ISSUE THREAD

**Issue by meek0** [obiba/ng-obiba-mica#962]
Currently, the result is sorted by dceId which is of the form `dce:1:1`. This does not reflect the population's and dce's weight.

Tentative solution would be to add a field reflecting this in the metadata and sort the dce's by that field. Do so either client-side or server-side.

**Comment by kazoompa** [comment]
Possible schema: client provides the current locale so that the sort key can be based on the acronym: _acronym[en] + poplationWeight + dceWeight_.

**Comment by sofiyad** [comment]
1st sort the DCE as desired
2nd republish the study and its corresponding datasets
